# Generated by Django 3.0.8 on 2020-08-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20200806_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='name',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AlterField(
            model_name='visitdetails',
            name='duration',
            field=models.CharField(choices=[('1 hour', '1 hour'), ('2 hours', '2 hours'), ('3 hours', '3 hours'), ('4 hours', '4 hours'), ('5 hours', '5 hours'), ('10 hours', '10 hours'), ('12 hours', '12 hours'), ('1 day', '1 day'), ('1 week', '1 week'), ('1 month', '1 month'), ('5 month', '5 month'), ('1 year', '1 year')], max_length=20),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='Phone_no',
            field=models.IntegerField(default=' ', max_length=10),
        ),
    ]
