# Generated by Django 3.0.8 on 2020-08-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0007_auto_20200806_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='Phone_no',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
