# Generated by Django 3.0.8 on 2020-08-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20200806_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_date_time',
            field=models.DateField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='host',
            name='flat_no',
            field=models.IntegerField(default=0),
        ),
    ]
