# Generated by Django 3.0.8 on 2020-08-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20200808_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitdetails',
            name='purpose',
            field=models.CharField(choices=[('Guest', 'Guest'), ('Home_Service', 'Home_Service'), ('Clients', 'Clients'), ('Delivery_Service', 'Delivery_Service'), ('General_service', 'General_service')], max_length=30),
        ),
    ]
